name: Get Auth Token

on:
    push:
      branches:
        - "f/99999_getAuthtoken"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.19.3]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  repository: TestDelevelop/editProjects
                  path: ./
                  ref: main
                  token: '${{ secrets.PAT }}'

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: sudo apt-get install -y libgtk-3.0 libgbm-dev libnss3 libatk-bridge2.0-0 libasound2

            - name: Create dot env file
              shell: bash
              run: |
                touch .env
                echo "TEST_AUTH=${{ secrets.TEST_AUTH }}" >> .env

            - name: npm set
              run: |
                  npm ci
            - name: npm set
              run: |
                  sudo apt-get install rhino

            - name: display Auth Token
              run: |
                  js src/js/test.js